extends Node

signal settings_changed
signal language_changed(language: StringName)
signal audio_changed(enabled: bool)
signal graphics_mode_changed(mode: StringName)

const DEFAULT_LANGUAGE: StringName = &"it"

const _TRANSLATIONS := {
	"it": {
		"main.status_chip": "IMMUNE DEFENSE PROTOCOL",
		"main.tagline": "Un nucleo vivente resiste a ondate di virus e batteri, adattando la propria biologia in tempo reale.",
		"main.hero_note": "Un solo nucleo al centro dell'arena. Ogni run e una risposta immune diversa, costruita tra mutazioni, DNA e pressione crescente.",
		"main.hero_brief": "Difendi il nucleo, ottimizza la biologia e lancia la prossima risposta immune.",
		"main.feature.auto": "AUTO-SHOOTER BIOLOGICO",
		"main.feature.mutations": "MUTAZIONI RUNTIME",
		"main.feature.meta": "META PROGRESSION DNA",
		"main.profile": "DNA accumulato: %d\nMiglior risposta immune: wave %d",
		"main.hint": "Costruisci la tua cellula nel Laboratorio, poi entra in arena con una build sempre piu efficiente.",
		"main.intel": "Boss ogni 10 wave. Mutazioni a milestone fisse. Cristalli DNA appaiono in arena e alimentano il Laboratorio.",
		"main.social.title": "Social Hub",
		"main.social.note": "Prototipo account link: apre il provider nel browser e salva lo stato locale del collegamento.",
		"main.social.note_compact": "Tocca un canale per collegarlo localmente.",
		"main.social.summary": "Account collegati: %d / %d",
		"main.social.link": "Collega",
		"main.social.confirm": "Conferma",
		"main.social.unlink": "Scollega",
		"main.social.pending_compact": "%s in verifica locale.",
		"main.social.linked_compact": "%s collegato localmente.",
		"main.social.pending_message": "DNA Reservoir: %d\nBest Immune Response: wave %d\n%s aperto nel browser. Premi ancora per confermare il link locale.",
		"main.social.linked_message": "DNA Reservoir: %d\nBest Immune Response: wave %d\n%s collegato nel profilo locale.",
		"common.play": "Play",
		"common.laboratory": "Laboratorio",
		"common.daily_missions": "Missioni Daily",
		"common.season_event": "Evento Stagionale",
		"common.shop": "Shop",
		"common.ops_center": "Ops Center",
		"common.account": "Account",
		"common.options": "Opzioni",
		"common.main_menu": "Menu Principale",
		"common.exit": "Esci",
		"common.launch_run": "Avvia Run",
		"common.claim": "Riscatta",
		"common.claimed": "Riscattato",
		"common.in_progress": "In corso",
		"common.claim_reward": "Riscatta Reward",
		"common.restart": "Ricomincia",
		"common.wave": "Wave",
		"main.quick_title": "Protocol Hub",
		"main.quick_note": "Le scelte profonde esistono ancora, ma ora vivono in scene dedicate piu leggibili: seleziona la destinazione e mantieni il menu principale rapido.",
		"main.deck_title": "Command Deck",
		"main.intel.loadout": "Loadout: %s | %s",
		"main.intel.daily": "Daily pronte: %d",
		"main.intel.event": "Evento: %d / %d   Claim %d",
		"main.intel.ops": "Pass claim: %d   Offers: %d",
		"main.daily_ready": "pronte",
		"main.exit_note": "Chiudi sessione",
		"main.social.ribbon": "Rete Operativa",
		"main.account_button": "Account Center",
		"main.account_guest": "Profilo guest attivo",
		"main.account_pending": "Verifica account in corso",
		"main.account_linked": "%s collegato",
		"main.signal.dna": "DNA %d",
		"main.signal.best": "Wave %d",
		"main.signal.loadout": "%s | %s",
		"main.signal.live": "%d claim | %d offers",
		"main.signal.shop": "FREE %d | OFF %d",
		"main.signal.network": "Rete %d/%d",
		"main.badge.ready": "%d pronti",
		"main.badge.progress": "%d/%d",
		"main.panel.loadout": "Loadout",
		"main.panel.live": "Feed Tattico",
		"main.panel.shop": "DNA Shop",
		"main.shop_meta": "Video %d   Offers %d",
		"main.battle_button": "BATTAGLIA",
		"main.battle_hint": "Apri il Prep Bay prima dell'ingaggio e lancia la prossima difesa.",
		"main.resume_button": "RIPRENDI RUN",
		"main.resume_hint": "Run salvata alla wave %d. Riprendi la difesa oppure apri il Prep Bay per una nuova risposta.",
		"main.rail.lab_tag": "DNA",
		"main.rail.daily_tag": "24H",
		"main.rail.event_tag": "EVENT",
		"main.rail.shop_tag": "STORE",
		"main.rail.ops_tag": "LIVE",
		"main.rail.system_tag": "SYS",
		"main.rail.exit_tag": "OFF",
		"main.rail.lab_title": "LAB",
		"main.rail.daily_title": "DAILY",
		"main.rail.event_title": "EVENTO",
		"main.rail.shop_title": "SHOP",
		"main.rail.ops_title": "OPS",
		"main.rail.system_title": "SYS",
		"main.rail.exit_title": "ESCI",
		"main.card.deploy": "DEPLOY",
		"main.card.play_subtitle": "Apri il Prep Bay, scegli l'assetto e lancia la prossima risposta immune.",
		"main.card.lab_subtitle": "Spendi DNA, rinforza il nucleo e costruisci il prossimo salto di potenza.",
		"main.card.daily_subtitle": "Missioni veloci, claim immediati e reward utili alla progressione quotidiana.",
		"main.card.season_subtitle": "Milestone stagionali, valuta evento e DNA bonus da conquistare in run.",
		"main.card.shop_subtitle": "Acquista pacchetti DNA, riscatti lampo e DNA gratuito tramite rewarded video.",
		"main.card.ops_subtitle": "Battle pass, offer deck e strumenti di tuning per il layer live del progetto.",
		"main.card.options_subtitle": "Audio, lingua e impostazioni di profilo in una schermata di sistema dedicata.",
		"lab.title": "Laboratorio Cellulare",
		"lab.subtitle": "Spendi il DNA raccolto nelle run per potenziare in modo permanente gli attributi del nucleo e sbloccare nuove mutazioni.",
		"lab.dna_block": "DNA disponibile: %d\nMiglior record: wave %d",
		"lab.summary": "Bonus permanenti della prossima run:\nDanno %.1f\nVelocita Attacco %.2f\nHP %.0f\nScudo %.0f\nRigenerazione %.1f/s\nATP x%.2f\nDNA x%.2f\nPickup Radius %.0f\nTargeting %.0f",
		"lab.category.attack": "Attacco",
		"lab.category.defense": "Difesa",
		"lab.category.utility": "Utility",
		"lab.category.mutation": "Mutazioni",
		"lab.blurb.attack": "Incrementa la letalita iniziale e la pressione offensiva del nucleo.",
		"lab.blurb.defense": "Migliora sopravvivenza, stabilita cellulare e recupero.",
		"lab.blurb.utility": "Espande raccolta risorse ed efficienza della run.",
		"lab.blurb.mutation": "Sblocca nuove mutazioni disponibili nel pool runtime.",
		"hud.shop_title": "Adaptive Upgrades",
		"hud.shop_hint": "Runtime",
		"hud.attack": "Attacco",
		"hud.defense": "Difesa",
		"hud.utility": "Utility",
		"hud.mutations": "Mutazioni",
		"hud.subtitle.attack": "Danno, traiettorie e output offensivo.",
		"hud.subtitle.defense": "Integrita, scudi e risposta al contatto.",
		"hud.subtitle.utility": "Raccolta, economia ed evoluzione automatica.",
		"hud.subtitle.mutation": "Effetti biologici speciali attivi nella run.",
		"hud.no_mutations": "Nessuna mutazione attiva.",
		"hud.hp": "HP %.0f / %.0f",
		"hud.shield": "Scudo %.0f / %.0f",
		"hud.arena_ready": "Arena pronta",
		"hud.menu": "MENU",
		"hud.boss_wave": "BOSS WAVE   Minacce %d",
		"hud.boss_in": "Minacce %d   Boss tra %d",
		"hud.no_bonus": "Nessun bonus attivo",
		"game_over.report": "RUN REPORT",
		"game_over.title": "Run Terminata",
		"game_over.summary": "Wave %d\nNemici Eliminati %d\nElite %d   Boss %d\nCristalli DNA %d\nDNA Guadagnato %d\nRecord %d",
		"mutation.report": "GENE RECOMBINATION",
		"mutation.title": "Scegli una Mutazione",
		"mutation.subtitle": "1 scelta su 3",
		"pause.title": "Menu di Gioco",
		"pause.subtitle": "Metti in sicurezza la run, regola le opzioni o torna subito all'arena.",
		"pause.continue": "Continua",
		"pause.save": "Salva",
		"pause.options": "Opzioni",
		"pause.exit": "Esci",
		"pause.save_done": "Run salvata nel profilo locale.",
		"pause.resume_loaded": "Run salvata ripristinata.",
		"pause.options_hint": "Audio, grafica e lingua si aggiornano in tempo reale.",
		"pause.language_updated": "Lingua aggiornata.",
		"prep.title": "Prep Bay",
		"prep.subtitle": "Scegli archetype del nucleo e settore di difesa subito prima di entrare in arena.",
		"prep.core_title": "Core Archetype",
		"prep.core_note": "L'archetype definisce skill attiva e vantaggi iniziali della run.",
		"prep.chapter_title": "Defense Sector",
		"prep.chapter_note": "Ogni settore modifica pressione nemica, resa DNA e identita visiva dell'arena.",
		"prep.briefing_title": "Briefing rapido",
		"prep.briefing_body": "1. Scegli il Core Archetype.\n2. Seleziona il Defense Sector.\n3. Avvia la run e difendi il nucleo raccogliendo ATP e DNA.",
		"prep.summary": "Core selezionato: %s\nSkill attiva: %s\nSettore: %s\nMoltiplicatori: DNA x%.2f | ATP x%.2f",
		"daily.title": "Daily Missions",
		"daily.subtitle": "Obiettivi rapidi per aumentare la retention e alimentare il loop meta con reward immediate.",
		"daily.status": "DNA %d   Reward pronte %d",
		"daily.progress": "Progress %d / %d   Reward %d DNA",
		"daily.fallback": "Missione giornaliera",
		"mission.kills": "Elimina %d patogeni",
		"mission.wave": "Raggiungi la wave %d",
		"mission.runtime_upgrades": "Acquista %d upgrade runtime",
		"mission.mutations": "Seleziona %d mutazioni",
		"mission.bosses": "Abbatti %d boss",
		"season.name": "Spring Recombination",
		"season.subtitle": "Evento stagionale a tempo con spore di ricombinazione e milestone DNA.",
		"season.currency": "Spore",
		"season.title": "Season Event",
		"season.progress": "Progress %d / %d %s   DNA %d",
		"season.reward": "Reward %d DNA",
		"shop.title": "DNA Shop",
		"shop.subtitle": "Monetizzazione prototipale pronta per IAP e rewarded ads: pacchetti DNA, offerte lampo e video gratuiti.",
		"shop.status": "DNA %d   Video %d   Offers %d",
		"shop.rewarded_title": "DNA Gratuito",
		"shop.rewarded_subtitle": "Guarda un rewarded video per ottenere DNA extra senza spendere valuta reale.",
		"shop.rewarded_status": "Reward %d DNA   Rimanenti %d / %d",
		"shop.rewarded_claim": "Guarda Video",
		"shop.rewarded_done": "Limite Giornaliero",
		"shop.rewarded_granted": "Rewarded video riscattato. DNA totale %d",
		"shop.packs_title": "Pacchetti DNA",
		"shop.packs_subtitle": "Acquisti in app prototipali pronti per essere collegati a Google Play Billing.",
		"shop.flash_title": "Offerte Lampo",
		"shop.flash_subtitle": "Claim rapidi e finestre live da usare come acceleratori di progressione.",
		"shop.buy_pack": "Acquista",
		"shop.flash_claim": "Riscatta Offerta",
		"shop.purchase_done": "Pacchetto DNA aggiunto. Totale DNA %d",
		"shop.offer_done": "Offerta riscattata. Totale DNA %d",
		"shop.purchase_count": "Acquisti test",
		"shop.pack.starter_bundle.title": "Starter Bundle",
		"shop.pack.starter_bundle.body": "DNA base %d\nBonus %d\nTotale %d DNA",
		"shop.pack.gene_cache.title": "Gene Cache",
		"shop.pack.gene_cache.body": "DNA base %d\nBonus %d\nTotale %d DNA",
		"shop.pack.genome_vault.title": "Genome Vault",
		"shop.pack.genome_vault.body": "DNA base %d\nBonus %d\nTotale %d DNA",
		"ops.title": "Ops Center",
		"ops.subtitle": "Fase 2 e fase 3 confluiscono qui: battle pass, offer deck, analytics locali e remote config di tuning.",
		"ops.status": "Pass claim %d   Offers %d   DNA %d",
		"ops.reload": "Ricarica Config",
		"ops.pass.name": "Adaptive Response Pass",
		"ops.pass.subtitle": "Progressione stagionale leggera per le sessioni di difesa.",
		"ops.pass.progress": "Progress %d / %d   Prossimo target %d",
		"ops.offers.title": "Offer Deck",
		"ops.offers.subtitle": "Offerte prototipali di live ops, pensate come hook da soft launch e reward loop.",
		"ops.analytics.title": "Analytics Snapshot",
		"ops.analytics.summary": "Sessioni %d   Run %d   Best wave %d   DNA totale %d   Avg run %ds",
		"ops.config.title": "Remote Config",
		"ops.config.summary": "ATP x%.2f   DNA x%.2f\nEnemy HP x%.2f   Enemy SPD x%.2f   Spawn x%.2f\nRevive charges %d   DNA boost x%.2f",
		"offer.starter_sample_kit.title": "Starter Sample Kit",
		"offer.starter_sample_kit.description": "Pacchetto una tantum di DNA puro per accelerare il Laboratorio.",
		"offer.response_drop.title": "Response Drop",
		"offer.response_drop.description": "Drop giornaliero di supporto con DNA immediato.",
		"offer.spore_exchange.title": "Spore Exchange",
		"offer.spore_exchange.description": "Scambio rapido che converte il traffico live in progresso evento.",
		"offer.pass_booster.title": "Pass Booster",
		"offer.pass_booster.description": "Spinta gratuita per far avanzare l'Adaptive Response Pass.",
		"options.title": "Opzioni",
		"options.subtitle": "Configura audio, lingua e progressione locale del profilo.",
		"options.profile": "DNA %d   Record wave %d",
		"options.audio_title": "Audio",
		"options.audio_on": "Audio: Si",
		"options.audio_off": "Audio: No",
		"options.graphics_title": "Grafica Mobile",
		"options.graphics_note": "Auto usa il profilo sicuro su Android per evitare artefatti come linee e banding sui device più sensibili.",
		"options.graphics_cycle": "Profilo grafico: %s",
		"options.language_title": "Lingua di gioco",
		"options.language_note": "La lingua aggiorna l'interfaccia del gioco e dei menu principali.",
		"options.reset_title": "Reset Profilo",
		"options.reset_desc": "Azzera DNA, record e tutti gli acquisti del Laboratorio. Impostazioni, collegamenti social e account restano invariati.",
		"options.reset_button": "Reset Progressi",
		"options.reset_confirm": "Premi di nuovo per confermare il reset",
		"options.reset_done": "Progressi del gioco azzerati.",
		"account.title": "Account Center",
		"account.subtitle": "Gestisci accesso, registrazione BackDoor Heroes e stato del profilo. La registrazione diretta usa backend remoto, invio mail al supporto e codice di verifica al giocatore.",
		"account.status_guest": "Stato: Guest locale",
		"account.status_pending_google": "Stato: Google in attesa di backend",
		"account.status_pending_backdoor": "Stato: verifica BackDoor Heroes in corso",
		"account.status_authenticated": "Stato: autenticato con %s",
		"account.google_title": "Google Login",
		"account.google_note": "Flusso predisposto lato client. Per autenticazione reale su Android serve collegare OAuth, SHA-1 e backend/sessione.",
		"account.google_button": "Apri Google",
		"account.google_pending": "Browser Google aperto. Per un login reale serve completare l'integrazione OAuth lato backend.",
		"account.google_device_started": "Flusso Google avviato. Completa l'accesso nel browser e poi torna nel gioco per verificare lo stato.",
		"account.google_waiting": "Login Google non ancora completato. Torna al browser, termina l'accesso e poi verifica di nuovo.",
		"account.google_expired": "La richiesta Google e scaduta. Avvia un nuovo login.",
		"account.google_unavailable": "Google login non disponibile: abilita il device flow nel backend.",
		"account.google_check_status": "Ho completato nel browser",
		"account.google_device_hint": "Codice accesso: %s\nApri: %s",
		"account.backdoor_title": "Registrazione BackDoor Heroes",
		"account.backdoor_note": "Compila nome, email e località. Il backend invia una mail a info.backdoorheros@gmail.com e spedisce al giocatore un codice casuale da confermare nel gioco.",
		"account.name_placeholder": "Nome giocatore",
		"account.email_placeholder": "Email giocatore",
		"account.location_placeholder": "Località giocatore",
		"account.code_placeholder": "Codice di verifica",
		"account.send_request": "Invia richiesta",
		"account.verify_code": "Conferma codice",
		"account.logout": "Disconnetti",
		"account.pending_hint": "Richiesta in sospeso per %s\nEmail: %s\nLocalità: %s\nInviata: %s",
		"account.authenticated_hint": "Profilo attivo: %s\nEmail: %s\nLocalità: %s",
		"account.backdoor_mail_opened": "Richiesta BackDoor Heroes inviata. Controlla la tua email per ricevere il codice di verifica.",
		"account.verified": "Account BackDoor Heroes verificato.",
		"account.backend_not_configured": "Registrazione online non configurata. Inserisci un backend remoto o abilita il fallback locale solo per sviluppo.",
		"account.error_name_required": "Inserisci un nome giocatore.",
		"account.error_invalid_email": "Inserisci una email valida.",
		"account.error_location_required": "Inserisci una località valida.",
		"account.error_code_required": "Inserisci il codice ricevuto via email.",
		"account.error_invalid_code": "Il codice inserito non coincide con la richiesta in sospeso.",
		"account.error_too_many_attempts": "Troppi tentativi errati. Avvia una nuova richiesta di registrazione.",
		"account.error_request_throttled": "Hai già inviato una richiesta da poco. Attendi prima di richiederne un'altra.",
		"account.error_backend_unreachable": "Backend auth non raggiungibile. Controlla URL, deploy e connessione.",
		"ftue.title": "Briefing di Prima Risposta",
		"ftue.subtitle": "Questa prima run ti mostra il flusso base del protocollo immunitario.",
		"ftue.progress": "Step %d / %d",
		"ftue.back": "Indietro",
		"ftue.next": "Avanti",
		"ftue.start": "Avvia Difesa",
		"ftue.skip": "Salta briefing",
		"ftue.page1.title": "Proteggi il nucleo",
		"ftue.page1.body": "Virus e batteri entrano dai bordi e convergono verso il centro. Se raggiungono il nucleo, subisci danni.",
		"ftue.page2.title": "Raccogli energia biologica",
		"ftue.page2.body": "Elimina i patogeni, raccogli ATP e cristalli DNA, poi usa le risorse per accelerare la build durante la run.",
		"ftue.page3.title": "Adatta la risposta immune",
		"ftue.page3.body": "Compra Adaptive Upgrades dal pannello inferiore e scegli una mutazione quando la wave raggiunge una milestone.",
		"ftue.page4.title": "Skill attiva",
		"ftue.page4.body": "Il nucleo spara da solo. Tu decidi il timing dell'abilita %s per alleggerire la pressione e salvare il centro.",
		"lang.it": "Italiano",
		"lang.en": "English",
		"graphics.auto": "Auto",
		"graphics.elite": "Elite",
		"graphics.safe": "Safe"
	},
	"en": {
		"main.status_chip": "IMMUNE DEFENSE PROTOCOL",
		"main.tagline": "A living core resists waves of viruses and bacteria while adapting its biology in real time.",
		"main.hero_note": "One core at the center of the arena. Every run becomes a new immune response shaped by mutations, DNA and escalating pressure.",
		"main.hero_brief": "Defend the core, optimize its biology and launch the next immune response.",
		"main.feature.auto": "BIO AUTO-SHOOTER",
		"main.feature.mutations": "RUNTIME MUTATIONS",
		"main.feature.meta": "DNA META PROGRESSION",
		"main.profile": "DNA Reservoir: %d\nBest Immune Response: wave %d",
		"main.hint": "Shape your cell in the Laboratory, then enter the arena with an ever-stronger build.",
		"main.intel": "Boss every 10 waves. Mutation milestones at fixed intervals. DNA crystals appear in the arena and feed the Laboratory.",
		"main.social.title": "Social Hub",
		"main.social.note": "Prototype account link: opens the provider in the browser and stores local connection state.",
		"main.social.note_compact": "Tap a channel to link it locally.",
		"main.social.summary": "Connected accounts: %d / %d",
		"main.social.link": "Connect",
		"main.social.confirm": "Confirm",
		"main.social.unlink": "Unlink",
		"main.social.pending_compact": "%s awaiting local confirmation.",
		"main.social.linked_compact": "%s linked locally.",
		"main.social.pending_message": "DNA Reservoir: %d\nBest Immune Response: wave %d\n%s opened in your browser. Press again to confirm the local link.",
		"main.social.linked_message": "DNA Reservoir: %d\nBest Immune Response: wave %d\n%s linked in the local profile.",
		"common.play": "Play",
		"common.laboratory": "Laboratory",
		"common.daily_missions": "Daily Missions",
		"common.season_event": "Season Event",
		"common.shop": "Shop",
		"common.ops_center": "Ops Center",
		"common.account": "Account",
		"common.options": "Options",
		"common.main_menu": "Main Menu",
		"common.exit": "Exit",
		"common.launch_run": "Launch Run",
		"common.claim": "Claim",
		"common.claimed": "Claimed",
		"common.in_progress": "In Progress",
		"common.claim_reward": "Claim Reward",
		"common.restart": "Restart",
		"common.wave": "Wave",
		"main.quick_title": "Protocol Hub",
		"main.quick_note": "The same systems remain available, but now they live in focused scenes so the main menu stays fast and legible.",
		"main.deck_title": "Command Deck",
		"main.intel.loadout": "Loadout: %s | %s",
		"main.intel.daily": "Daily ready: %d",
		"main.intel.event": "Event: %d / %d   Claim %d",
		"main.intel.ops": "Pass claims: %d   Offers: %d",
		"main.daily_ready": "ready",
		"main.exit_note": "Close session",
		"main.social.ribbon": "Operational Network",
		"main.account_button": "Account Center",
		"main.account_guest": "Guest profile active",
		"main.account_pending": "Account verification pending",
		"main.account_linked": "%s linked",
		"main.signal.dna": "DNA %d",
		"main.signal.best": "Wave %d",
		"main.signal.loadout": "%s | %s",
		"main.signal.live": "%d claims | %d offers",
		"main.signal.shop": "FREE %d | OFF %d",
		"main.signal.network": "Network %d/%d",
		"main.badge.ready": "%d ready",
		"main.badge.progress": "%d/%d",
		"main.panel.loadout": "Loadout",
		"main.panel.live": "Tactical Feed",
		"main.panel.shop": "DNA Shop",
		"main.shop_meta": "Videos %d   Offers %d",
		"main.battle_button": "BATTLE",
		"main.battle_hint": "Open the Prep Bay before deployment and launch the next defense.",
		"main.resume_button": "RESUME RUN",
		"main.resume_hint": "Saved run at wave %d. Resume the defense or open the Prep Bay for a fresh response.",
		"main.rail.lab_tag": "DNA",
		"main.rail.daily_tag": "24H",
		"main.rail.event_tag": "EVENT",
		"main.rail.shop_tag": "STORE",
		"main.rail.ops_tag": "LIVE",
		"main.rail.system_tag": "SYS",
		"main.rail.exit_tag": "OFF",
		"main.rail.lab_title": "LAB",
		"main.rail.daily_title": "DAILY",
		"main.rail.event_title": "EVENT",
		"main.rail.shop_title": "SHOP",
		"main.rail.ops_title": "OPS",
		"main.rail.system_title": "SYS",
		"main.rail.exit_title": "EXIT",
		"main.card.deploy": "DEPLOY",
		"main.card.play_subtitle": "Open the Prep Bay, choose your loadout and launch the next immune response.",
		"main.card.lab_subtitle": "Spend DNA, reinforce the core and build the next jump in power.",
		"main.card.daily_subtitle": "Quick missions, instant claims and rewards that support daily progression.",
		"main.card.season_subtitle": "Seasonal milestones, event currency and bonus DNA earned through runs.",
		"main.card.shop_subtitle": "Buy DNA packs, claim flash offers and earn free DNA through rewarded videos.",
		"main.card.ops_subtitle": "Battle pass, offer deck and tuning tools for the live layer of the project.",
		"main.card.options_subtitle": "Audio, language and profile settings in a dedicated system screen.",
		"lab.title": "Cellular Laboratory",
		"lab.subtitle": "Spend DNA earned in runs to permanently enhance the core and unlock new mutations.",
		"lab.dna_block": "Available DNA: %d\nBest record: wave %d",
		"lab.summary": "Persistent bonuses for the next run:\nDamage %.1f\nAttack Speed %.2f\nHP %.0f\nShield %.0f\nRegeneration %.1f/s\nATP x%.2f\nDNA x%.2f\nPickup Radius %.0f\nTargeting %.0f",
		"lab.category.attack": "Attack",
		"lab.category.defense": "Defense",
		"lab.category.utility": "Utility",
		"lab.category.mutation": "Mutations",
		"lab.blurb.attack": "Increase starting lethality and offensive pressure.",
		"lab.blurb.defense": "Improve survival, stability and recovery.",
		"lab.blurb.utility": "Expand resource collection and run efficiency.",
		"lab.blurb.mutation": "Unlock additional mutations for the runtime pool.",
		"hud.shop_title": "Adaptive Upgrades",
		"hud.shop_hint": "Runtime",
		"hud.attack": "Attack",
		"hud.defense": "Defense",
		"hud.utility": "Utility",
		"hud.mutations": "Mutations",
		"hud.subtitle.attack": "Damage, trajectories and offensive output.",
		"hud.subtitle.defense": "Integrity, shields and contact response.",
		"hud.subtitle.utility": "Collection, economy and automatic evolution.",
		"hud.subtitle.mutation": "Special biological effects active during the run.",
		"hud.no_mutations": "No active mutations.",
		"hud.hp": "HP %.0f / %.0f",
		"hud.shield": "Shield %.0f / %.0f",
		"hud.arena_ready": "Arena ready",
		"hud.menu": "MENU",
		"hud.boss_wave": "BOSS WAVE   Threats %d",
		"hud.boss_in": "Threats %d   Boss in %d",
		"hud.no_bonus": "No active bonus",
		"game_over.report": "RUN REPORT",
		"game_over.title": "Run Over",
		"game_over.summary": "Wave %d\nEnemies Eliminated %d\nElites %d   Bosses %d\nDNA Crystals %d\nDNA Earned %d\nRecord %d",
		"mutation.report": "GENE RECOMBINATION",
		"mutation.title": "Choose a Mutation",
		"mutation.subtitle": "1 choice out of 3",
		"pause.title": "Game Menu",
		"pause.subtitle": "Secure the run, tweak options or jump straight back into the arena.",
		"pause.continue": "Continue",
		"pause.save": "Save",
		"pause.options": "Options",
		"pause.exit": "Exit",
		"pause.save_done": "Run saved to the local profile.",
		"pause.resume_loaded": "Saved run restored.",
		"pause.options_hint": "Audio, graphics and language update in real time.",
		"pause.language_updated": "Language updated.",
		"prep.title": "Prep Bay",
		"prep.subtitle": "Choose your core archetype and defense sector right before entering the arena.",
		"prep.core_title": "Core Archetype",
		"prep.core_note": "Your archetype defines active skill identity and starting advantages.",
		"prep.chapter_title": "Defense Sector",
		"prep.chapter_note": "Each sector changes enemy pressure, reward yield and arena flavor.",
		"prep.briefing_title": "Quick briefing",
		"prep.briefing_body": "1. Choose a Core Archetype.\n2. Select a Defense Sector.\n3. Launch the run and defend the core while collecting ATP and DNA.",
		"prep.summary": "Selected core: %s\nActive skill: %s\nSector: %s\nMultipliers: DNA x%.2f | ATP x%.2f",
		"daily.title": "Daily Missions",
		"daily.subtitle": "Short-form goals that strengthen retention and keep the meta loop paying out.",
		"daily.status": "DNA %d   Rewards ready %d",
		"daily.progress": "Progress %d / %d   Reward %d DNA",
		"daily.fallback": "Daily mission",
		"mission.kills": "Eliminate %d pathogens",
		"mission.wave": "Reach wave %d",
		"mission.runtime_upgrades": "Buy %d runtime upgrades",
		"mission.mutations": "Pick %d mutations",
		"mission.bosses": "Defeat %d bosses",
		"season.name": "Spring Recombination",
		"season.subtitle": "Limited-time seasonal event with recombination spores and DNA milestones.",
		"season.currency": "Spores",
		"season.title": "Season Event",
		"season.progress": "Progress %d / %d %s   DNA %d",
		"season.reward": "Reward %d DNA",
		"shop.title": "DNA Shop",
		"shop.subtitle": "Prototype monetization layer ready for IAP and rewarded ads: DNA packs, flash offers and free video rewards.",
		"shop.status": "DNA %d   Videos %d   Offers %d",
		"shop.rewarded_title": "Free DNA",
		"shop.rewarded_subtitle": "Watch a rewarded video to gain bonus DNA without spending premium currency.",
		"shop.rewarded_status": "Reward %d DNA   Remaining %d / %d",
		"shop.rewarded_claim": "Watch Video",
		"shop.rewarded_done": "Daily Limit Reached",
		"shop.rewarded_granted": "Rewarded video claimed. Total DNA %d",
		"shop.packs_title": "DNA Packs",
		"shop.packs_subtitle": "Prototype in-app purchases ready to be wired into Google Play Billing.",
		"shop.flash_title": "Flash Offers",
		"shop.flash_subtitle": "Quick claim windows and live offers built as progression accelerators.",
		"shop.buy_pack": "Purchase",
		"shop.flash_claim": "Claim Offer",
		"shop.purchase_done": "DNA pack added. Total DNA %d",
		"shop.offer_done": "Offer claimed. Total DNA %d",
		"shop.purchase_count": "Test purchases",
		"shop.pack.starter_bundle.title": "Starter Bundle",
		"shop.pack.starter_bundle.body": "Base DNA %d\nBonus %d\nTotal %d DNA",
		"shop.pack.gene_cache.title": "Gene Cache",
		"shop.pack.gene_cache.body": "Base DNA %d\nBonus %d\nTotal %d DNA",
		"shop.pack.genome_vault.title": "Genome Vault",
		"shop.pack.genome_vault.body": "Base DNA %d\nBonus %d\nTotal %d DNA",
		"ops.title": "Ops Center",
		"ops.subtitle": "Phase 2 and Phase 3 now live here: battle pass, offer deck, local analytics and remote config tuning hooks.",
		"ops.status": "Pass claims %d   Offers %d   DNA %d",
		"ops.reload": "Reload Config",
		"ops.pass.name": "Adaptive Response Pass",
		"ops.pass.subtitle": "Light seasonal progression layered on top of each defense session.",
		"ops.pass.progress": "Progress %d / %d   Next target %d",
		"ops.offers.title": "Offer Deck",
		"ops.offers.subtitle": "Prototype live offers designed as soft-launch hooks and reward cadence tests.",
		"ops.analytics.title": "Analytics Snapshot",
		"ops.analytics.summary": "Sessions %d   Runs %d   Best wave %d   Total DNA %d   Avg run %ds",
		"ops.config.title": "Remote Config",
		"ops.config.summary": "ATP x%.2f   DNA x%.2f\nEnemy HP x%.2f   Enemy SPD x%.2f   Spawn x%.2f\nRevive charges %d   DNA boost x%.2f",
		"offer.starter_sample_kit.title": "Starter Sample Kit",
		"offer.starter_sample_kit.description": "A one-time pure DNA pack to accelerate the Laboratory.",
		"offer.response_drop.title": "Response Drop",
		"offer.response_drop.description": "A daily support crate with instant DNA.",
		"offer.spore_exchange.title": "Spore Exchange",
		"offer.spore_exchange.description": "A quick exchange that converts live traffic into event progress.",
		"offer.pass_booster.title": "Pass Booster",
		"offer.pass_booster.description": "A free push for the Adaptive Response Pass.",
		"options.title": "Options",
		"options.subtitle": "Configure audio, language and local profile progression.",
		"options.profile": "DNA %d   Best wave %d",
		"options.audio_title": "Audio",
		"options.audio_on": "Audio: On",
		"options.audio_off": "Audio: Off",
		"options.graphics_title": "Mobile Graphics",
		"options.graphics_note": "Auto uses the safe mobile profile on Android to reduce artifacts such as horizontal lines and banding on sensitive devices.",
		"options.graphics_cycle": "Graphics profile: %s",
		"options.language_title": "Game Language",
		"options.language_note": "Language updates the core UI across menus and the in-run interface.",
		"options.reset_title": "Reset Profile",
		"options.reset_desc": "Clears DNA, records and all Laboratory purchases. Settings, social links and account stay untouched.",
		"options.reset_button": "Reset Progress",
		"options.reset_confirm": "Press again to confirm the reset",
		"options.reset_done": "Game progress reset.",
		"account.title": "Account Center",
		"account.subtitle": "Manage sign-in, BackDoor Heroes registration and profile status. Direct registration uses a remote backend, support email notification and a player verification code.",
		"account.status_guest": "Status: Local guest",
		"account.status_pending_google": "Status: Google awaiting backend",
		"account.status_pending_backdoor": "Status: BackDoor Heroes verification pending",
		"account.status_authenticated": "Status: authenticated with %s",
		"account.google_title": "Google Login",
		"account.google_note": "Client-side flow is prepared. Real Android authentication still needs OAuth, SHA-1 and backend/session wiring.",
		"account.google_button": "Open Google",
		"account.google_pending": "Google browser opened. A real login still requires the backend OAuth integration to be completed.",
		"account.google_device_started": "Google flow started. Finish the sign-in in your browser, then return to the game and check the status.",
		"account.google_waiting": "Google login is not complete yet. Finish the browser flow and check again.",
		"account.google_expired": "The Google request expired. Start a new sign-in flow.",
		"account.google_unavailable": "Google login is unavailable: enable device flow in the backend config.",
		"account.google_check_status": "I finished in browser",
		"account.google_device_hint": "Access code: %s\nOpen: %s",
		"account.backdoor_title": "BackDoor Heroes Registration",
		"account.backdoor_note": "Fill in name, email and location. The backend emails info.backdoorheros@gmail.com and sends the player a random code to confirm inside the game.",
		"account.name_placeholder": "Player name",
		"account.email_placeholder": "Player email",
		"account.location_placeholder": "Player location",
		"account.code_placeholder": "Verification code",
		"account.send_request": "Send request",
		"account.verify_code": "Verify code",
		"account.logout": "Log out",
		"account.pending_hint": "Pending request for %s\nEmail: %s\nLocation: %s\nSent: %s",
		"account.authenticated_hint": "Active profile: %s\nEmail: %s\nLocation: %s",
		"account.backdoor_mail_opened": "BackDoor Heroes request sent. Check your inbox for the verification code.",
		"account.verified": "BackDoor Heroes account verified.",
		"account.backend_not_configured": "Online registration is not configured. Add a remote backend or enable local fallback only for development.",
		"account.error_name_required": "Enter a player name.",
		"account.error_invalid_email": "Enter a valid email address.",
		"account.error_location_required": "Enter a valid location.",
		"account.error_code_required": "Enter the code received by email.",
		"account.error_invalid_code": "The inserted code does not match the pending request.",
		"account.error_too_many_attempts": "Too many wrong attempts. Start a new registration request.",
		"account.error_request_throttled": "A request was already sent recently. Wait before sending another one.",
		"account.error_backend_unreachable": "Auth backend unreachable. Check URL, deploy and network.",
		"ftue.title": "First Response Briefing",
		"ftue.subtitle": "This first run walks you through the basic immune-defense loop.",
		"ftue.progress": "Step %d / %d",
		"ftue.back": "Back",
		"ftue.next": "Next",
		"ftue.start": "Launch Defense",
		"ftue.skip": "Skip briefing",
		"ftue.page1.title": "Protect the core",
		"ftue.page1.body": "Viruses and bacteria enter from the arena edge and collapse toward the center. If they reach the core, you take damage.",
		"ftue.page2.title": "Harvest biological energy",
		"ftue.page2.body": "Eliminate pathogens, collect ATP and DNA crystals, then reinvest those resources to accelerate your build during the run.",
		"ftue.page3.title": "Adapt the immune response",
		"ftue.page3.body": "Buy Adaptive Upgrades from the bottom panel and pick a mutation whenever the wave reaches a milestone.",
		"ftue.page4.title": "Active skill timing",
		"ftue.page4.body": "The core fires automatically. Your job is to time %s to release pressure and save the center.",
		"lang.it": "Italian",
		"lang.en": "English",
		"graphics.auto": "Auto",
		"graphics.elite": "Elite",
		"graphics.safe": "Safe"
	}
}

var audio_enabled: bool = true
var language: StringName = DEFAULT_LANGUAGE
var graphics_mode: StringName = &"auto"

func _ready() -> void:
	load_settings()
	_apply_audio_state()

func load_settings() -> void:
	var save_data := SaveManager.get_save()
	var settings := save_data.get("settings", {}) as Dictionary
	audio_enabled = bool(settings.get("audio_enabled", true))
	language = StringName(settings.get("language", String(DEFAULT_LANGUAGE)))
	graphics_mode = StringName(settings.get("graphics_mode", "auto"))
	if not _TRANSLATIONS.has(String(language)):
		language = DEFAULT_LANGUAGE
	if not get_available_graphics_modes().has(graphics_mode):
		graphics_mode = &"auto"

func save_settings() -> void:
	SaveManager.write_save({
		"settings": {
			"audio_enabled": audio_enabled,
			"language": String(language),
			"graphics_mode": String(graphics_mode)
		}
	})

func set_audio_enabled(enabled: bool) -> void:
	audio_enabled = enabled
	_apply_audio_state()
	save_settings()
	audio_changed.emit(audio_enabled)
	settings_changed.emit()

func toggle_audio() -> void:
	set_audio_enabled(not audio_enabled)

func set_language(new_language: StringName) -> void:
	if not _TRANSLATIONS.has(String(new_language)):
		return
	language = new_language
	save_settings()
	language_changed.emit(language)
	settings_changed.emit()

func get_available_languages() -> Array[StringName]:
	return [&"it", &"en"]

func get_available_graphics_modes() -> Array[StringName]:
	return [&"auto", &"elite", &"safe"]

func get_language_display_name(language_id: StringName) -> String:
	return t("lang.%s" % String(language_id))

func get_graphics_mode_display_name(mode: StringName) -> String:
	return t("graphics.%s" % String(mode))

func set_graphics_mode(new_mode: StringName) -> void:
	if not get_available_graphics_modes().has(new_mode):
		return
	graphics_mode = new_mode
	save_settings()
	graphics_mode_changed.emit(graphics_mode)
	settings_changed.emit()

func cycle_graphics_mode() -> void:
	var modes := get_available_graphics_modes()
	var index := modes.find(graphics_mode)
	if index < 0:
		index = 0
	set_graphics_mode(modes[(index + 1) % modes.size()])

func use_mobile_safe_visuals() -> bool:
	match graphics_mode:
		&"safe":
			return true
		&"elite":
			return false
		_:
			return OS.get_name() == "Android"

func t(key: String) -> String:
	var lang_dict := _TRANSLATIONS.get(String(language), {}) as Dictionary
	if lang_dict.has(key):
		return String(lang_dict[key])
	var fallback := _TRANSLATIONS.get(String(DEFAULT_LANGUAGE), {}) as Dictionary
	return String(fallback.get(key, key))

func _apply_audio_state() -> void:
	var master_index: int = AudioServer.get_bus_index("Master")
	if master_index < 0:
		master_index = 0
	AudioServer.set_bus_mute(master_index, not audio_enabled)
